### ISSUE TITLE
Error when use bundler v2.1.0

### ISSUE THREAD

**Issue by ToBeDefined** [rvm/rubygems-bundler#68]
all ruby command running error when use [bundler 2.1.0](https://github.com/bundler/bundler/releases/tag/v2.1.0)

```
Traceback (most recent call last):
	10: from /Users/tbd/.rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:10:in `<main>'
	 9: from /Users/tbd/.rvm/gems/ruby-2.5.3/gems/executable-hooks-1.6.0/lib/executable-hooks/hooks.rb:49:in `run'
	 8: from /Users/tbd/.rvm/gems/ruby-2.5.3/gems/executable-hooks-1.6.0/lib/executable-hooks/hooks.rb:49:in `each'
	 7: from /Users/tbd/.rvm/gems/ruby-2.5.3/gems/executable-hooks-1.6.0/lib/executable-hooks/hooks.rb:50:in `block in run'
	 6: from /Users/tbd/.rvm/gems/ruby-2.5.3/gems/rubygems-bundler-1.4.5/lib/rubygems_executable_plugin.rb:4:in `block in <top (required)>'
	 5: from /Users/tbd/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:34:in `require'
	 4: from /Users/tbd/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
	 3: from /Users/tbd/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:130:in `require'
	 2: from /Users/tbd/.rvm/gems/ruby-2.5.3/gems/rubygems-bundler-1.4.5/lib/rubygems-bundler/noexec.rb:131:in `<top (required)>'
	 1: from /Users/tbd/.rvm/gems/ruby-2.5.3/gems/rubygems-bundler-1.4.5/lib/rubygems-bundler/noexec.rb:124:in `check'
/Users/tbd/.rvm/gems/ruby-2.5.3/gems/rubygems-bundler-1.4.5/lib/rubygems-bundler/noexec.rb:84:in `setup': undefined method `plain_specs' for #<Bundler::RubygemsIntegration:0x00007fa7150e8968> (NoMethodError)
```

**Comment by jirihradil** [comment]
Reporting the same! 

Happens when executing a remote command while deploy using Capistrano 2:

```
 ** [out :: 10.0.1.55] /home/ec2-user/.rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/rubygems-bundler-1.4.5/lib/rubygems-bundler/noexec.rb:84:in `setup':
 ** [out :: 10.0.1.55] undefined method `plain_specs' for #<Bundler::RubygemsIntegration:0x0000000001fe96c8> (NoMethodError)
 ** [out :: 10.0.1.55] from /home/ec2-user/.rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/rubygems-bundler-1.4.5/lib/rubygems-bundler/noexec.rb:124:in `check'
 ** [out :: 10.0.1.55] from /home/ec2-user/.rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/rubygems-bundler-1.4.5/lib/rubygems-bundler/noexec.rb:131:in `<top (required)>'
 ** [out :: 10.0.1.55] from /home/ec2-user/.rvm/rubies/ruby-2.4.4/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:130:in `require'
 ** [out :: 10.0.1.55] from /home/ec2-user/.rvm/rubies/ruby-2.4.4/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
 ** [out :: 10.0.1.55] from /home/ec2-user/.rvm/rubies/ruby-2.4.4/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:34:in `require'
 ** [out :: 10.0.1.55] from /home/ec2-user/.rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/rubygems-bundler-1.4.5/lib/rubygems_executable_plugin.rb:4:in `block in <top (required)>'
 ** [out :: 10.0.1.55] from /home/ec2-user/.rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/executable-hooks-1.5.0/lib/executable-hooks/hooks.rb:50:in `block in run'
 ** [out :: 10.0.1.55] from /home/ec2-user/.rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/executable-hooks-1.5.0/lib/executable-hooks/hooks.rb:49:in `each'
 ** [out :: 10.0.1.55] from /home/ec2-user/.rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/executable-hooks-1.5.0/lib/executable-hooks/hooks.rb:49:in `run'
 ** [out :: 10.0.1.55] from /home/ec2-user/.rvm/gems/ruby-2.4.4/bin/ruby_executable_hooks:10:in `<main>'
```

**Comment by silva96** [comment]
This issue has been reported also in bundler/bundler/issues/7488, we are facing it too.

**Comment by ToBeDefined** [comment]
bundler v2.1.1 Fixed
